import { Page } from "@playwright/test";
import { LoginPage } from "./LoginPage";
import { SideMenu } from "../Components/SideMenu";
import { BaseApplicationPage } from "./BaseApplicationPage";
import { HeaderHomeMenu } from "../Components/Home/HeaderHomeMenu";
import { FiltersModal } from "../Components/Home/Modals/FiltersModal";
import { CategoriesDetails } from "../Components/Categories/CategoriesDetails";
import { MainCatalog } from "../Components/Home/MainCatalog";
import { HeaderMenu } from "../Components/HeaderMenu";
import { ModifyPassword } from "../Components/UserMenu/UserPage/ModifyPassword";
import { ModifyPersonalDetails } from "../Components/UserMenu/UserPage/ModifyPersonalDetails"; 
import { UserDetails } from "../Components/UserMenu/UserPage/UserDetails"; 
import { UserPageHeaderMenu } from "../Components/UserMenu/UserPage/UserPageHeaderMenu";
import { QuoteHeader } from "../Components/Quote/QuoteHeader";
import { CustomFields } from "../Components/Quote/HomeCart/CustomFields";
import { Products } from "../Components/Quote/HomeCart/Products"; 
import { QuoteInfo } from "../Components/Quote/HomeCart/QuoteInfo"; 
import { Totals } from "../Components/Quote/HomeCart/Totals"; 
import { TotalSummary } from "../Components/Quote/HomeCart/TotalSummary"; 
import { InvolvedParties } from "../Components/Quote/InvolvedParties/InvolvedParties"; 
import { ShippingInfo } from "../Components/Quote/ShippingInfo/ShippingInfo";
import { ConfiguratorCommon } from "../Components/Configurator/ConfiguratorCommon";
import { ASUS_antonleonenko } from "../Components/Configurator/ProductsAttributes/ASUS_antonleonenko";


export class PageManager {
    page: Page; 
    loginPage;
    sideMenu; 
    baseApplicationPage;
    headerHomeMenu; 
    filtersModal; 
    categoriesDetails;
    mainCatalog;
    headerMenu;
    modifyPassword; 
    modifyPersonalDetails;
    userDetails; 
    userPageHeaderMenu;
    quoteHeader;
    customFields; 
    products; 
    quoteInfo; 
    totals; 
    totalSummary;
    involvedParties; 
    shippingInfo; 
    configuratorCommon;
    ASUS_antonleonenko;


    constructor(page) {
        this.page = page; 
        this.loginPage = new LoginPage(page); 
        this.sideMenu = new SideMenu(page); 
        this.baseApplicationPage = new BaseApplicationPage(page);
        this.headerHomeMenu = new HeaderHomeMenu(page); 
        this.filtersModal = new FiltersModal(page); 
        this.categoriesDetails = new CategoriesDetails(page);
        this.mainCatalog = new MainCatalog(page); 
        this.headerMenu = new HeaderMenu(page);
        this.modifyPassword = new ModifyPassword(page); 
        this.modifyPersonalDetails = new ModifyPersonalDetails(page); 
        this.userDetails = new UserDetails(page); 
        this.userPageHeaderMenu = new UserPageHeaderMenu(page); 
        this.quoteHeader = new QuoteHeader(page);
        this.customFields = new CustomFields(page); 
        this.products = new Products(page); 
        this.quoteInfo = new QuoteInfo(page); 
        this.totals = new Totals(page); 
        this.totalSummary = new TotalSummary(page); 
        this.involvedParties = new InvolvedParties(page); 
        this.shippingInfo = new ShippingInfo(page); 
        this.configuratorCommon = new ConfiguratorCommon(page); 
        this.ASUS_antonleonenko = new ASUS_antonleonenko(page); 
    };
};